### ISSUE TITLE
Relayer Near-Term Maintenance 

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/relayer#1]
- [ ] Testing Environments
  - [x] Dev-env - Bash Script Testing
  - [ ] Docker Based Testing
- [x] IBC-go Migration - cosmos/relayer#501
- [x] Remove light-client - cosmos/relayer#493
- [ ] Fix QueryTMProof - cosmos/relayer#508
- [x] Fix pagination issues in queries

**Comment by jackzampolin** [comment]
I think we are good here. Lets delay the docker based testing stuff till later and make that a whole thing.

**Comment by jtieri** [comment]
Agreed, we can open a separate issue focused solely on the docker based testing harness.
Closing this issue now :rocket: :sparkles:
